# Passar as variáveis de ambiente como variáveis de ambiente no container
spring:
  application:
    name: api
  flyway:
    locations: classpath:db/migrations/
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:postgresql://${SPRING_DATASOURCE_URL}/autenticacao
  jpa:
    show-sql: true
api:
  security:
    senha-assinatura-token: ${SENHA_ASSINATURA_JWT}