CREATE TABLE IF NOT EXISTS usuarios (
	id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	email VARCHAR(64) UNIQUE NOT NULL,
	nome VARCHAR(128) NOT NULL,
	senha VARCHAR(128) NOT NULL,
	is_admin BOOLEAN NOT NULL,
	is_ativo BOOLEAN NOT NULL
);