{
 "title": "dashboard-api-auth-prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"}, instance)"
    }
   },
   {
    "name": "pool",
    "label": "pool",
    "query": {
     "query": "label_values(hikaricp_connections{instance=\"$instance\"},pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Load average [1m]",
   "type": "timeseries",
   "description": "Média de uso de CPU no último minuto",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{application=\"$application\", instance=\"$instance\", job=\"api-autenticacao\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Utilização de CPU",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\", job=\"api-autenticacao\"}",
     "legendFormat": "Uso de CPU do sistema"
    },
    {
     "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\", job=\"api-autenticacao\"}",
     "legendFormat": "Uso de CPU do processo"
    }
   ]
  },
  { "title": "API Autenticação", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Errors & Warnings",
   "type": "timeseries",
   "description": "Logs de erro e de warnings nos ultimos 5 minutos",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(logback_events_total{application=\"$application\", job=\"api-autenticacao\", instance=\"$instance\", level=\"warn\"}[5m])",
     "legendFormat": "{{level}}"
    },
    {
     "expr": "increase(logback_events_total{level=\"error\", application=\"$application\", instance=\"$instance\", job=\"api-autenticacao\"}[5m])",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Autenticações",
   "type": "timeseries",
   "description": "Autenticações feitas nos ultimos 5 minutos",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "increase(auth_user_sucess_total{application=\"$application\", instance=\"$instance\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(auth_user_fails_total{application=\"$application\", instance=\"$instance\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de requisições",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"api-autenticacao\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "API Uptime",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "description": "Hora de inicio",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JDBC Pool",
   "type": "stat",
   "description": "Pool de conexões com o BD",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections{application=\"$application\", instance=\"$instance\", pool=\"$pool\", job=\"api-autenticacao\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}